import type { Menu, MenuCategory, MenuItem } from '../types/bookingCustomization'
import menuFallback from './menuFallback.json'

/**
 * Offline fallback for the menu catalog. Mirrors `public/menu.json` (generated by
 * `scripts/build_menu_catalog.py`, which also refreshes `menuFallback.json`).
 */

type CatalogSnapshot = {
  menus: Menu[]
  categories: MenuCategory[]
  items: MenuItem[]
}

const catalog = menuFallback as CatalogSnapshot

export const MOCK_MENUS: Menu[] = catalog.menus
export const MOCK_MENU_CATEGORIES: MenuCategory[] = catalog.categories
export const MOCK_MENU_ITEMS: MenuItem[] = catalog.items

const itemById = new Map(MOCK_MENU_ITEMS.map((m) => [m.id, m]))

export function getMenuItemById(id: string): MenuItem | undefined {
  return itemById.get(id)
}

export function menuItemsInCategory(categoryId: MenuItem['categoryId']): MenuItem[] {
  return MOCK_MENU_ITEMS.filter((m) => m.categoryId === categoryId)
}
